# Site Settings
title: 'busta.dev'
description: >-
  Busta Games Home Page
url: https://busta.games

# Build Settings
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "_sass"
  style: compressed

# Collection Settings
collections:
  games:
    output: true

defaults:
- scope:
    path: ""
    type: "games"
  values:
    permalink: "/:collection/:name/"

# Plugin Settings
highlighter: rouge